# Generated by Django 2.0.9 on 2018-11-25 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('informal', '0002_auto_20181123_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
